name: QA Automation Pipeline   # Name of the workflow

on:                            # When should it run?
  push:                        # Run whenever you push code
    branches:
      - main                   # Only on the 'main' branch

jobs:                          # Define jobs
  test:                        # Job name
    runs-on: ubuntu-latest     # GitHub provides a Linux VM

    steps:                     # Steps inside the job
      - name: Checkout Code
        uses: actions/checkout@v4   # Pulls your repo files

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11      # Installs Python 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt   # Installs Selenium

      - name: Run Selenium Tests
        run: python login_test.py   # Runs your test script
